<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHuvVAPC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHuvVAPC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHuvVAPC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHuvVAPC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHuvVAPC\App_KernelDevDebugContainer([
    'container.build_hash' => 'HuvVAPC',
    'container.build_id' => '2d259862',
    'container.build_time' => 1742941343,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHuvVAPC');
